mongo:
  # host: "192.168.60.21:27017,192.168.60.22:27017"
  # db: "test"
  # collection: "obsdata"
  host: "mongo1:27017,mongo2:27017"
  db: "test"
  collection: "obsdata"  
  
mysql:
  host: "localhost"
  user: "root"
  password: "Ie@123456"
  db: "ari"

  #host: "192.168.60.21"
  # user: "test"
  # password: "test@oper+123"
  # db: "NoSQL_DatatTest"

test:
  insert: false
  month: true
  station: false
  update: true