mongo:
  # host: "192.168.60.21:27017,192.168.60.22:27017"
  # db: "test"
  # collection: "obsdata"

  #host: "mongo1:27017,mongo2:27018"
  host: "localhost:27017"
  #host: "localhost:27017,localhost:27018"
  db: "test"
  collection: "obs_test"  
  
mysql:
  host: "localhost"
  user: "root"
  password: "Ie@123456"
  db: "ari"

  #host: "192.168.60.21"
  # user: "test"
  # password: "test@oper+123"
  # db: "NoSQL_DatatTest"

test:
  insert: true
  month: false
  station: false
  update: false